name = "galaxytunnel"
pages_build_output_dir = "."
compatibility_date = "2024-03-20"
compatibility_flags = [ "nodejs_compat" ]

[vars]
WS_PATH = "galaxy-tunnel"
PROXYIP = "galaxytunnel.cloud-ip.cc"

DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
UUID = "6836046c-1c7a-44c6-887d-62e7310ba0af"
